[package]
name = "program"
version = "0.1.0"
edition = "2021"

[dependencies]

solana-program = "2.1.22"

[dev-dependencies]
solana-program-test = "2.1.22"
solana-sdk = "2.1.22"

[lib]
crate-type = ["cdylib", "lib"]